microsoft/vscode-vsce

- README.md
I believe this is the proper docs url now.
> Proper docs url

- src/package.ts
- src/test/fixtures/readme/readme.images.expected.md
- src/test/package.test.ts
The optional parameter wasn't being passed when calling collect so baseImagesUrl and baseContentUrl weren't being respected.
I also added a test to verify that baseImagesUrl is handled properly by the processor.
> Added options to collect call in pack function

- package.json
Is it just me or is typescript missing in the devDependencies?
I always have to install it manually.
> added typescript devDependency

- src/npm.ts
- src/test/fixtures/devDependencies/node_modules/real/node_modules/real_sub/package.json
- src/test/fixtures/devDependencies/node_modules/real/package.json
- src/test/fixtures/devDependencies/node_modules/real2/package.json
- src/test/fixtures/devDependencies/node_modules/real_sub/package.json
- src/test/package.test.ts
We still have some problems with this `npm list`, but this should fix at least the problems in #64.
> removed --depth to fix #64

- src/publish.ts
This can be confusing to the user and they might not realize they can up the version number.
> Prompt the user to up the version number.

- src/main.ts
Addresses #90 which was a breaking change introduced by 6027e49 to fix #9
> Add --packagePath to publish command

- src/package.ts
- src/test/fixtures/readme/readme.expected.md
- src/test/fixtures/readme/readme.images.expected.md
- src/test/fixtures/readme/readme.md
> Added support for relative links with image title

- resources/extension.vsixmanifest
- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
> Display project information in Marketplace

- src/package.ts
- src/test/package.test.ts
> Make sure changelog files has his own asset Type

- package.json
- src/publish.ts
- src/util.ts
Comes with a cool streaming API which allows us to have larger extensions.
> Adopt the latest vso-node-api

- src/show.ts
there are a couple of ways to protect this scenario, not sure if this is the best way but it works.
> fixes #219

- src/package.ts
- src/test/package.test.ts
> Generate internal tags for language packs extensions

- resources/extension.vsixmanifest
- src/manifest.ts
- src/package.ts
> Populate extension pack property

- src/main.ts
I was quite confused by the previous description ('Location of the package'). I think it's worth being more explicit about what is being created.
> Changed --out flag description in package command

- src/package.ts
> Added support for the `VSCE_IGNORE_KEYWORDS_LENGTH` environment variable

- README.md
- src/main.ts
- src/package.ts
- src/validation.ts
@joaomoreno Please review but don't merge yet. I can merge it after I make the `/api` endpoints available.
> [DO NOT MERGE] Update links. Part of Microsoft/vscode-docs#2165

- .vscode/tasks.json
This is a proposed PR to fix the `compile` task. Please feel free to close if not approved.
> Fix compile task

- src/package.ts
updated error message to resolve https://github.com/microsoft/vscode-vsce/issues/351
> added note about vscodeignore to bundle reminder

- src/main.ts
- src/publish.ts
https://github.com/microsoft/vscode-vsce/issues/364
> Allow commit message to be specified

- src/main.ts
Refactored the respective code snippet to a more concise version.
> Minor refactor resulting in concise code

- src/store.ts
This won't fix permissions if .vsce already exists, so maybe this isn't a complete fix?
> Set permissions on .vsce to 0600; fix for #230

- src/publish.ts
I know it was a few seconds before. But now it is a few minutes.
> Modifying messages to match the current situation

- src/npm.ts
> Support linked npm modules

- package.json
- yarn.lock
> Fixed markdown-it security vulnerability

- package.json
- src/main.ts
- yarn.lock
> Migrate to a better matching engine

- src/package.ts
- src/test/package.test.ts
Fixes https://github.com/microsoft/vscode-vsce/issues/389
> Allow badges from Github Workflows

- src/package.ts
- src/test/fixtures/readme/readme.expected.md
- src/test/fixtures/readme/readme.github.expected.md
- src/test/fixtures/readme/readme.github.md
- src/test/fixtures/readme/readme.images.expected.md
- src/test/fixtures/readme/readme.md
Resolves #228
Updated some tests and they all pass.
> Prevent mailto links from being joined with prefix

- src/main.ts
> fix: handle unknown args

- src/package.ts
- src/test/package.test.ts
Add a tag product-icon-theme for contribution productIconThemes
> Support productIconThemes

- .dockerignore
- Dockerfile
- README.md
* Added Dockerfile and docker-ignore
* Updated README file for usage
> Added Dockerfile for docker support

- src/store.ts
> chore: improve error message

- src/package.ts
> Do not ignore README.md

- src/package.ts
- src/test/package.test.ts
> update regex to support repository shorthand

- src/main.ts
- src/package.ts
- src/publicgalleryapi.ts
- src/publish.ts
- src/test/package.test.ts
- Update deriving extension kind from package.json (Sync with VS Code)
- Add web extension tag if extension is a web extension 
- Remove experimental web publishing support
> Support web extensions

- src/package.ts
tag extension packs as web extensions
> tag extension packs as web extensions

- src/package.ts
- src/test/package.test.ts
Validate and throw error if extension kind has invalid values
> validate extension kind

- src/main.ts
- src/package.ts
- src/publish.ts
- src/test/package.test.ts
- Add --pre-release flag
- Add PreRelease property to vsix
> feat: add --pre-release flag and support

- src/publish.ts
Fixes - https://github.com/microsoft/vscode-vsce/issues/665
validate the package if pre-release flag is passed and the package is not a pre-release version
> validate the package if pre-release flag is passed

- src/api.ts
Fixes #667
Add preRelease flag to api
> Add preRelease flag to api

- src/package.ts
- src/test/package.test.ts
> Include prerelease flag for engine while checking

- src/main.ts
- src/package.ts
- src/publish.ts
Closes:
- https://github.com/microsoft/vscode-vsce/issues/700
- https://github.com/microsoft/vscode-vsce/issues/706
> Add flags to support automation in edge cases

- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
> feat: support sponsoring extension

- src/main.ts
- src/publish.ts
A solution to #775. The PR adds new flag, checks for this flag on related errors
> feat: allow to skip publishing duplicate package

- src/main.ts
- src/package.ts
- src/search.ts
- src/show.ts
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/vscode-vsce/commit/9cd1fc6357701f1a1491a89076efa22766d9804c#commitcomment-91005270
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/vscode-vsce/commit/1cdafe949c96e2eeaa44546940f8947cae01b3b3
> chore: Spelling

- src/publish.ts
> feat: allow publishing universal target alongside platform specific targets

- package-lock.json
- package.json
> keytar should be optional

- src/package.ts
> allow badges from vsmarketplacebadges.dev

- .gitignore
- .npmignore
- .vscode/settings.json
- api-extractor.json
- package-lock.json
- package.json
- src/api.ts
- src/package.ts
- src/publish.ts
Also:
- run `npm audit fix`
- version bump
Fixes #800
> Fix .d.ts API

- src/api.ts
- src/package.ts
> api: stop ignoring `packageManager` option

- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
> feat: adopt implicit activation events

- src/package.ts
> Don't append .js extension to .cjs files

- README.md
Alternative option to #829, resolves #828,
> mention yarn testing requirement in docs

- src/package.ts
we should also consider making it a warning with a yes/no prompt to continue without editing
> fix https://github.com/microsoft/vscode/issues/175292

- package-lock.json
- package.json
- src/publish.ts
> Look for an exact match of version+platform when detecting duplicates

- src/package.ts
PR made in Codespaces and I didn't set up signing there, hence the Unverified label.
> Add CodeQL suppression comment

- src/main.ts
- src/package.ts
- src/publish.ts
- src/test/package.test.ts
> feat: add support for packaging and publishing without license file

- src/show.ts
> cleanup show command

- src/package.ts
- src/test/package.test.ts
> handle multi line images

- src/main.ts
- src/package.ts
- src/publish.ts
- src/test/package.test.ts
> feat: support --readme-path and --changelog-path

- src/show.ts
> show pre-release data in show command

- src/show.ts
> feat: show targets in show command

- src/package.ts
> fixes #322

- src/test/validation.test.ts
> Add more version validation tests

- src/package.ts
Do not validate translations when there is no NLS fle
Fixes #981
> Fix "No translation found" error when executing `vsce package`

- src/package.ts
- src/test/package.test.ts
> Auto Assign Chat Participant Tag

- src/package.ts
- src/test/package.test.ts
> Fix readme-path handling

- src/package.ts
> Fix tree printing to respect the out option

- src/package.ts
- src/test/package.test.ts
- src/typings/parse-semver.d.ts
> Updated the semver comparison

- src/package.ts
```Copilot Generated Description:``` Introduce a new tools tag for the languageModelTools contribution in the TagsProcessor.
closes https://github.com/microsoft/vscode-vsce/issues/1119
> Add tools tag for languageModelTools contribution

- src/store.ts
```Copilot Generated Description:``` Enhance the error handling in the Personal Access Token verification process to provide clearer and more specific error messages.
related https://github.com/microsoft/vscode-vsce/issues/1118
> Improve error message for Personal Access Token verification

- src/package.ts
```Copilot Generated Description:``` Implement validation for entry point files to ensure they exist and are not ignored, enhancing error handling during the processing of manifests.
> Proper entry point validation

- src/main.ts
```Copilot Generated Description:``` Update the description of the unpublish command to specify that it removes an extension from the marketplace.
closes https://github.com/microsoft/vscode-vsce/issues/1143
> Clarify unpublish command description

- build/azure-pipelines.oss.yml
```Copilot Generated Description:``` Introduce a new pipeline configuration for building and testing across multiple operating systems.
> Add OSS pipeline

- package-lock.json
- package.json
```Copilot Generated Description:``` Update the chalk dependency to version 4.1.2.
related https://github.com/microsoft/vscode-vsce/pull/1111
related #1110
> Update chalk version to 4.1.2

- src/package.ts
```Copilot Generated Description:``` Enhance the error message for missing entrypoints to provide clearer guidance on ensuring files are included in the "files" field of 'package.json' or not ignored by '.vscodeignore'.
> Improve error message for missing entrypoints

- build/azure-pipelines.oss.yml
- build/build.oss.yml
Verification build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=348771&view=results
> chore: onboard OSS pipeline to 1ES template

- src/package.ts
> fix: check exec params
