- src/npm.ts
The user can set a default value for --depth with:
~~~~~~~~
npm config set depth 0
~~~~~~~~
But we want to ignore this, although `--depth` is ignored when used with `--parseable`.
My original pull request didn't took this into account, because I forgot that @felixfbecker mentioned it in https://github.com/Microsoft/vscode-vsce/issues/52#issuecomment-183679060.
> set --depth to 9999 to ignore user settings, when listing dependencies

- src/npm.ts
To resolve #72.
Maybe the warning should be outputted directly at the start of vsce.
> Output warning when using bad npm version

- package.json
- src/package.ts
- src/test/package.test.ts
@joaomoreno Here are a couple fixes for #94. 
First I changed the hidden tag to be '__' instead of '$'. That was easy. 
The second task I'm having a harder time with and could use your help. An issue we saw with the MP algorithm was javascript extensions being tagged with java. I attempted to fix that by sorounding the regex with '\b' - that solves the "java" issue but introduced a "c++" tagging issue. 
The test is failing now on tagging an extension as "c++". Would love if you could take a look at it. 
Some things I tried. 
- Escaping the regex per instructions [here](http://stackoverflow.com/questions/2593637/how-to-escape-regular-expression-in-javascript) and [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) - because "+" is a regex character. …
> Issue 93 change hidden tag

- gulpfile.js
- package.json
- src/package.ts
- src/test/package.test.ts
From @waderyan, #93
MP folks are running an implementation of this pseudocode on the INT database. Once we confirm the data looks good we'll run it on prod. 
We will want to bring full parity with what happens on update for VSCE. The psuedocode is [here](https://github.com/Microsoft/vscode-marketplace/blob/master/tag-seeding-algorithm.js).
Couple things that have evolved since #83. 
My thought is let's wait until MP engineers run this on the INT environment before we make the changes. 
Small update from MP.
> Full parity on keywords with MP

- package.json
- src/package.ts
- src/test/package.test.ts
The following PR will address #126 that is - if a changelog file is present in your directory, it will make sure to treat it as an asset (which can be used around the ecosystem).
Notes are in the code!
> Make vsce recognise changelog.md as an asset

- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
We want to be defensive when it comes to proposed API and one part of this is to not allow extensions to be published unless `enableProposedApi` is off.
> check for enableProposedApi and don't allow to publish

- src/main.ts
Changed description of option `--baseImagesUrl` of the package command from:
"Prepend all relative image links in README.md **will with** this url."
to
"Prepend all relative image links in README.md **with** this url."
> fixed description in option baseImagesUrl of package command

- src/package.ts
- src/publish.ts
- src/test/package.test.ts
Fixes #158 
I've prepared a PR with maybe a naive implementation. Let me know if that works. The idea is to provide an option for the readManifest function to only read the manifest without applying the translation parsing. Then in the versionBump we're using this to do the overwriting without issues.
> Fix manifest overriding

- src/package.ts
A lot of extensions are published with the keyword `javsacript`  and I think this is the reason why.
> Fixed javascript typo

- src/package.ts
I think [VersionEye](http://www.versioneye.com) should be a trusted source, this service allows easy dependency checking and can prevent security vulnerabilities from creeping in javascript based projects, which means it could easily be used by any VSCode extension that has some code in it.
> Add www.versioneye.com to trusted SVG sources

- src/main.ts
- src/search.ts
- src/viewutils.ts
This pr adds `vsce` “search” command.
```bash
$ vsce search perl
$ vsce search perl —json
```
Ref: #216
> WIP: feature/issue-216-add-search-command

- src/show.ts
Tags may contain file extensions prefixed `__ext_` we filter those out from the tags list
* added file extension tag filter
* guard show arguments with default values
fixes #222
> Hide file extension tags in "show" command

- src/show.ts
- src/viewutils.ts
Both cmd and powershell fails to render the super nice unicode stars. It breaks my hearts... to make windows users use a fallback.
The issue circles unicode glyphs not in raster etc. fonts and the use of charpages.
fixes #221
> fix show: add icon fallback on win32

- src/publicgalleryapi.ts
The `extensionId` should not be case sensitive. *Matching a search on the Marketplace.*
fixes #224
> fix "show" to be case insensitive

- src/main.ts
- src/package.ts
This fixes an issue where `npm list` thinks dependencies are invalid,
but a project uses Yarn and this can correctly handle the dependencies.
This is blocking SQL Ops Studio extensions that rely on
https://github.com/anthonydresser/dataprotocol-client, as this is marked
as invalid and essentially requires use of Yarn.
Please let me know if there's anything I should be doing in terms of testing etc. to help validate this. The basic test of using `vsce package --yarn` worked as expected and no longer caused packaging to fail.
> Support Yarn use in package command

- src/package.ts
- src/publish.ts
Resolves #206 
References #180 
As per popular request `vsce publish <version>` will now use `npm version <version>`, in order to bump the package version. In the process, `package-lock.json` will also be updated (when using `npm5+`) and tagged `git` commit will be done (supporting `gpg` signing when it's set in `git` config).
**Note:** As before only `major`, `minor` and `patch` are supported as a valid ` <version>`.
I refrained from implementing a rollback of the process, as if anything goes wrong after the version bump (i.e. network issues), the user can simply execute `vsce publish` (without ` <version>`) and complete the publishing.
This implementation also does not interfere with using plain `vsce publish` via a CI service. Tthe user, in that case, should perform `npm version …
> Add ability to publish using  'npm version'

- src/publish.ts
- src/util.ts
Provide some guidance to the user as to the URL of the plugin.
> Show URL of published extension when it is successful

- resources/extension.vsixmanifest
- src/package.ts
- src/test/package.test.ts
Related to https://github.com/Microsoft/vscode/pull/58563
This PR adds a new property to the vsixmanifest that contains the localized names of the languages supported by the extension.
> Add property for supported languages

- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
This is a follow up to #286
We have been using the wrong property name there.
> Use localizedLanguageName instead of languageNameLocalized

- yarn.lock
On Nodejs 10.14 and 11, `gulp compile` will run into error 
```
ReferenceError: internalBinding is not defined
```
Upgrade npm packages to fix above issue. Upstream related issue is https://github.com/gulpjs/gulp/issues/2246
> yarn upgrade for nodejs natives compability issue

- package.json
- src/main.ts
- src/npm.ts
- src/package.ts
- src/publish.ts
- src/show.ts
- src/store.ts
- src/util.ts
- yarn.lock
Fixes #323
Didn't test the message itself on macOS.
Also didn't test it in general since I don't know how.
> Add colors to console messages

- src/package.ts
This for https://github.com/Microsoft/vscode-vsce/issues/333 and suggests to bundle when having an extension with more than 100 files. The limit 100 is a bit arbitrary tbh, open for other suggestions. 50? 1000?
> Suggest bundling when having many files

- src/package.ts
I maintain the Visual Studio Code extension for Bazel, Google's open-source build system (https://github.com/bazelbuild/vscode-bazel). Our CI host is [buildkite.com](https://buildkite.com/) ([pipeline](https://buildkite.com/bazel/vscode-bazel-vs-bazel)) and I would like to add their badge host to the list of trusted SVG sources (see [README.md](https://raw.githubusercontent.com/bazelbuild/vscode-bazel/master/README.md) for example).
> Add badge.buildkite.com to trusted SVG sources

- src/package.ts
- src/test/validation.test.ts
- src/validation.ts
See context at https://github.com/microsoft/vscode/issues/71048.
> Check @types/vscode version against engines.vscode

- package.json
`@types/commander` package is deprecated.
commander provides its own type definitions and it is not required to install `@types/commander` as from the official [npm package repository](https://www.npmjs.com/package/@types/commander) page.
> Remove stub type definition for commander

- src/main.ts
Fixes #349 
Fixed the usage information that showed up with  `--help` which was misleading previously.
`vsce --help` shows:-
```md
Usage: vsce <command> [options]
Options:
-V, --version                        output the version number
-h, --help                           output usage information
Commands:
ls [options]                         Lists all the files that will be published
package [options]                    Packages an extension
publish [options] [<version>]        Publishes an extension
unpublish [options] [<extensionid>]  Unpublishes an extension. Example extension id: microsoft.csharp.
ls-publishers                        List all known publishers
create-publisher <publisher>         Creates a new publisher
delete-publisher <publisher>         Deletes a publisher
login …
```
> Show up usage information the right way

- src/viewutils.ts
Use `process.platform` instead of `os.platform() `to maintain consistency.
> fix(chore): Minor refactor

- src/main.ts
Log level for outdated version notice is changed from "WARNING" to "INFO". See screenshot. 
This addresses issue #367
> Changed log level to info.

- src/package.ts
- src/test/fixtures/readme/readme.github.expected.md
- src/test/fixtures/readme/readme.github.md
- src/test/package.test.ts
Closes #340:
* Enable to replace GitHub issue references with absolute urls
* Supports to replace issue links of shape `#7` as well as `Microsoft/vscode#7`
* Do not replace anything if it is no GitHub repository
* Added unit tests
There is no conflict between _issues_ and _pull requests_ because GitHub redirects issue urls automatically to prs. For example: `https://github.com/microsoft/vscode-vsce/issues/248` will be redirected to https://github.com/microsoft/vscode-vsce/pulls/248  
If you have any questions, do not hestiate to ask me.
> Support GitHub Issue Links

- src/package.ts
Uses yarn for the prepublish step if `--yarn` is specified on the command line
/cc @joaomoreno
> Honors --yarn flag for prepublish step

- src/package.ts
- src/test/package.test.ts
"Resolves" #391
I put "Resolves" into quotes since it's not really a bug, I just think this improves the experience. The case that a readme is unchanged was also never tested, so I added a test as well. 
@joaomoreno maybe you want to have a look at this and add your 2 cents? :) thank you.
> Improve error message when packaging an extension with an unchanged README.md

- src/package.ts
- src/test/fixtures/readme/readme.expected.md
- src/test/fixtures/readme/readme.images.expected.md
- src/test/fixtures/readme/readme.md
On Issue Request #192 
Please review the changes. If anything is wrong please guide me. [I'm a newbie]
> [Added] Relative sources in <img> tags in README.md are not rewritten to absolute URLs

- src/package.ts
I improved the package path option.
If the given package output path is just a directory, it will be concatenated with the default file name (`{manifest.name}-${manifest.version}.vsix`) to write the VSIX file.
If it's a concrete file path, that will be used.
Otherwise, the default behaviour will be used. (current working directory with package name and version)
Hope you like it. Thanks for merging! 😊
> if package path is a directory, use default file name to write vsix

- src/manifest.ts
- src/package.ts
Fixes https://github.com/microsoft/vscode-vsce/issues/403
@sandy081:
- This currently only emits a warning, doesn't prevent publishing... should it?
- I believe we need a better user facing message, maybe with a better link describing the adoption and the purpose of that property.
> Warns the extension authors of `extensionKind` type change

- src/main.ts
- src/publish.ts
> fixes #400 allow force to unpublish an extension

- src/npm.ts
* Changed log level to error instead of warning for `npm list` command
> Log level for npm list command changed to error to increase compatibility

- src/main.ts
- src/package.ts
- src/test/package.test.ts
Adds an option to `vsce package` to prevent any expansion of GitHub issue references.
**Note**: This is a workaround for https://github.com/microsoft/vscode-vsce/issues/398, but is not a fix for that issue.
> Add --noGitHubIssueLinking to stop issue link expansion in package step

- src/package.ts
Azure DevOps is reporting this warning as an error.  Since this message is not really a warning, just a notification of which package tool is being used, it can be changed to `console.log`
> Change a console.warn to console.log for an informational message

- src/package.ts
> print output of failed prepublish scripts #441

- src/main.ts
This change adds a default value to the `-p` (`--pat`) option for the publish command based on an environmental variable.
Making this change creates an implicit default value for providing a personal access token, making it easier to trigger VSCE releases from CI platforms where global installation of modules is not possible (i.e. publish a VSCE extension via an `npm run...` command).
> Support injecting PAT from an environmental variable

- package.json
The `out` directory is not present directly after checkout and so running `yarn watch` fails.
```
~/w/c/vscode-vsce ❯❯❯ yarn watch                                                                                     ✘ 1
yarn run v1.15.2
$ cp src/vsce out/vsce && tsc --watch
cp: out/vsce: No such file or directory
error Command failed with exit code 1.
```
This fixes the issue by making sure the `out` directory exists
> Fix issues with missing out directory

- .vscode/launch.json
When I worked on debugging https://github.com/microsoft/vscode-vsce/issues/432#issuecomment-650148223, I needed to make the extension work locally. This configuration change was very useful for running a local development version to package an extension.
> Update launch.json to be useful for extension debugging

- src/main.ts
- src/package.ts
- src/publish.ts
- src/test/fixtures/readme/readme.branch.expected.md
- src/test/fixtures/readme/readme.branch.main.expected.md
- src/test/fixtures/readme/readme.branch.override.content.expected.md
- src/test/fixtures/readme/readme.branch.override.images.expected.md
- src/test/package.test.ts
Fixes #468 
Currently if `repository` in `package.json` is set to a GitHub URL, all the relative links in `README.md` get converted to absolute links but they always refer to the `master` branch. This change adds a flag `githubBranch` which allows the user to override this assumption without having to use to override `baseImagesUrl` and `baseContentUrl`.
The `baseImageUrl` and `baseContentUrl` options take precedence over `githubBranch`, so doing something like: `vsce --githubBranch main --baseImagesUrl http://blah` will only change non-image relative links to stem from the `main`.
> Add githubBranch flag to control the branch for GitHub relative links

- src/main.ts
While troubleshooting why we can't publish Vim to the marketplace, we found we have to bundle it ourselves and then upload through the marketplace portal. It would be great if the options of `publish` and `package` align.
> support --web in vsce package

- azure-pipelines.yml
- src/main.ts
- src/npm.ts
- src/package.ts
- src/test/package.test.ts
This adds automatic detection of `yarn` based on the presence of either a `yarn.lock` or `.yarnrc` file in the current directory. Passing `--yarn` or `--no-yarn` disables automatic detection.
Fixes #480
> Adds detection for yarn, and '--no-yarn' to suppress detection

- src/package.ts
- src/test/package.test.ts
VSC requires the manifest file unpacked from the .vsix archive to be
marked as writable (see [1]). Since generating writable artifacts is
difficult in some build systems (such as Bazel), it would be helpful if
vsce itself could ensure that the file mode of the manifest is correct.
With this commit, the correct file mode on `package.json` is set
automatically by the packaging process via a new `Processor` and yazl's
`mode` argument.
[1]: https://github.com/microsoft/vscode/blob/88144f6d31718288c7a2c6fb741e0646d40804cf/src/vs/platform/extensionManagement/node/extensionsScanner.ts#L144
> Ensure package.json is writable in *.vsix

- src/main.ts
From [v5.0.0](https://github.com/tj/commander.js/releases/tag/v5.0.0), Commander.js displays an error message for a missing subcommand by default.
> chore: remove stale code

- src/test/fixtures/nls/package.nls.json
> Fix typo in package.nls.json

- src/main.ts
- src/store.ts
> Add verify-pat command

- README.md
- src/package.ts
- src/test/fixtures/readme/readme.default.md
- src/test/package.test.ts
> Use HEAD as default branch rather than master

- src/main.ts
- src/package.ts
- src/publish.ts
- src/test/fixtures/readme/readme.gitlab.branch.main.expected.md
- src/test/fixtures/readme/readme.gitlab.branch.override.content.expected.md
- src/test/fixtures/readme/readme.gitlab.branch.override.images.expected.md
- src/test/fixtures/readme/readme.gitlab.default.md
- src/test/fixtures/readme/readme.gitlab.expected.md
- src/test/fixtures/readme/readme.gitlab.md
- src/test/package.test.ts
This MR:
- Adds support for recognizing GitLab.com repositories and correctly inferring `baseContentUrl` and `baseImagesUrl`. 
- Adds support for recognizing and replacing GitLab issue references with the correct URL
Caveats:
- GitLab allows subgroups, so `https://gitlab.com/foo/bar/baz.git` could be a valid repository.
- GitLab is adding a [special references](https://docs.gitlab.com/ee/user/markdown.html#special-gitlab-references) syntax, so in the future, issue references may also come in the form `[issue:123]`
I just duplicated the flags `--githubBranch` and `--no-gitHubIssueLinking` and associated code paths, `s/github/gitlab/`. It may be better to rename the flags instead of duplicating them, but I couldn't think of a good name for "Hosted Git server branch name". I thought about …
> Add support for GitLab.com

- src/package.ts
- src/test/package.test.ts
I want to use the `remote-menu` to get a list of extensions that contribute to the remote indicator menu
> add remote-menu tag

- src/publicgalleryapi.ts
In case of an invalid extension identifier, the error message from the backend is now properly displayed in the console:
> ERROR  The query supplied was not valid, one of the filters contained an error. The fully qualified name MUST contain a '.' between the publisher and extension names.
Fixes #563
> fix: Missing error response handling

- .vscode/extensions.json
- .vscode/settings.json
- azure-pipelines.yml
- package.json
- src/main.ts
- src/package.ts
- src/publish.ts
- src/test/fixtures/version/package.json
- src/test/package.test.ts
And add the `--no-git-tag-version` option to disable the creation of version commit and tag when calling `npm version`.
- Set prettier as the default formatter for JSON and Typescript files in VS Code and add it to the list of recommended extensions
- Improve `package --out` help message
- Format `main.ts` with Prettier
- Move `versionBump` from `publish.ts` to `package.ts` as it is where it is used first now
- Use `ts-node` with `mocha`
- Upgrade `tmp`
- Revamp the `package.json` scripts by simplifying and renaming some
> Allow version bump in package command

- package.json
The PR updates version of the `azure-devops-node-api` dependecy to `11.0.1` to pull in recent changes to remove fake credentials from the readme: https://github.com/microsoft/azure-devops-node-api/pull/453
The fake credentials trigger cred scanner alerts for internal products that depend on `vsce` and thus on `azure-devops-node-api` (like GH Codespaces and LiveShare extensions) [[ticket](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1323550/)].
> Update `azure-devops-node-api` version

- src/search.ts
Fixed the issue #605 where search returns ADO, VSIDE, un-published, or locked extensions along with VS Code extensions
> Fixed an issue where search returns ADO and VSIDE

- Dockerfile
- README.md
since the keytar was added as default, libsecret is a dependency
Fixes #645
> Add `libsecret` to `Dockerfile` and mention the dependency on `README`

- src/test/validation.test.ts
- src/validation.ts
Since we don't have control over the patch version (it's auto-incremented by DefinitelyTyped), we shouldn't look at the patch version at all.
> fix: only enforce major and minor version of types check

- src/package.ts
- src/test/package.test.ts
Fixes #670
With entrypoints 'main' and browser' it's increasingly possible to not have an entrypoint setup for packaging.  The chances increase since there tends to be a lot of refactoring to support both runtime environments.
This PR adds a quick check via a *Processor class to make sure that any entrypoint declared in the package is actually going to be present in the `extension` folder of the vsix.
Tests consistent with package.test.ts have been added.
> feat: sanity check to validate entrypoints

- src/package.ts
- src/test/package.test.ts
Fixes #675 
Validation of entry points is added In the last release #669. But there is a small edge case. 
Writing `.js` file extension in node environment is optional.  
People usually write `main: "out/extension"` which is actually `"out/extension.js"`.
So, the below condition will fail.
https://github.com/microsoft/vscode-vsce/blob/dc68cc89fe9c7ac0c690a5bc01175756c431e781/src/package.ts#L933
I fixed the bug and also added a test case for this situation in this PR.
> fix: entrypoint validation without js tag

- Dockerfile
Hi, I tested use this tools in Docker yesterday and I got the error output: 
``` bash
/opt/vsce/out/package.js:136
return (translations ?? [])
^
SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/opt/vsce/out/main.js:27:19)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
After I read the …
> fix: docker base image needs be at latest `node:14-alpine`

- .github/workflows/lint-pr.yaml
This adds a new workflow which lints PR titles, so that when using "squash and merge" in GH, we don't miss the semantics behind the changes.
cc @felipecrs
> ci: :sparkles: new PR lint workflow

- src/main.ts
- src/search.ts
PR to fix issue #727 
New search command usage
```
Usage: vsce search [options] <text>
search extension gallery
Options:
--json                  Output result in json format (default: false)
--stats                 Shows the extension rating and download counts (default: false)
-p, --pagesize [value]  Number of results to return (default: "100")
-h, --help              display help for comman
```
Result:
> feat: Search command improvements

- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
> fix: validate sponsor URL

- README.md
- src/main.ts
Commander documentation states that when using negative commands, if you do not already have a non-negative command it sets the default to `true`, which is what broke the logic for loading defaults from `package.json`.
Fixes: #742
Reference: https://www.npmjs.com/package/commander#other-option-types-negatable-boolean-and-booleanvalue
> fix: ensure that we can define dependency argument in config

- src/package.ts
- src/test/fixtures/readme/readme.branch.main.expected.md
- src/test/fixtures/readme/readme.branch.override.content.expected.md
- src/test/fixtures/readme/readme.branch.override.images.expected.md
- src/test/fixtures/readme/readme.default.md
- src/test/fixtures/readme/readme.expected.md
- src/test/fixtures/readme/readme.gitlab.branch.main.expected.md
- src/test/fixtures/readme/readme.gitlab.branch.override.content.expected.md
- src/test/fixtures/readme/readme.gitlab.branch.override.images.expected.md
- src/test/fixtures/readme/readme.gitlab.default.md
- src/test/fixtures/readme/readme.images.expected.md
- src/test/fixtures/readme/readme.md
This PR fixes #739 by taking the `#` character into account in image URLs.
When inserting images in a markdown file using the HTML tag, relative image URLs that contain a `#` character do not get prefixed with the base URL.
```html
```
Later when validating image URLs, a relative URL is passed to the `URL` constructor, which results in an error being thrown.
https://github.com/microsoft/vscode-vsce/blob/955c76056f8f173e8cef180936b8c11c42af6be9/src/package.ts#L779-L782
The regex responsible for replacing <img> links has been modified to support the `#` character.
I have also updated the test suite accordingly.
> fix: support fragments in image URLs

- src/main.ts
- src/package.ts
> fix: list all valid targets in documentation for --target

- src/publish.ts
> fix: clarify simultaneous use of packagePath and target in `vsce publish`

- .vscode/launch.json
Current `program` path does not exist (anymore, I guess).
> fix: correct program path in `launch.json`

- src/api.ts
- src/package.ts
- src/publish.ts
This PR introduces modifications to allow the API methods to use all options currently supported by the CLI.
The following modifications have been made:
1. The `createVSIX` function now accepts an `IPackageOptions` instead of `ICreateVSIXOptions`
2. The existing `ICreateVSIXOptions` has been kept in the file and refactored to stay backward compatible.
3. The `ICreateVSIXOptions` has been marked as deprecated to encourage using `IPackageOptions` instead.
1. The `publishVSIX` function still accepts an `IPublishOptions` but it's currently an alias to the `IPublishOptions` type declared in `publish.ts`
2. The `IPublishVSIXOptions` has been refactored to extend from `IPublishOptions` and also includes the needed `target` property.
This should in _theory_ be backward compatible because all …
> feat: expose all options to packaging and publishing APIs

- src/manifest.ts
- src/package.ts
- src/test/package.test.ts
Added the support for extension authors label an extension as `FREE` or `FREE TRIAL`
#748
> feat: support pricing model in the manifest file

- src/publish.ts
I did some testing on local by using a dummy `package.json` and this appears to work.
Test environments:
Windows 11 | Git Bash | Running `./vsce` directly -> no interactive prompt, does not unpublish
Windows 11 | Git Bash | Running with `winpty ./vsce` -> interactive prompts, works as expected
Windows 11 | Powershell | Running with `node vsce` -> interactive prompts, works as expected
Did not test WSL/Linux or Mac, but I can't imagine the behavior is different.
> feat: prompt for full name to confirm unpublish action (#782)

- src/package.ts
- src/test/package.test.ts
* Supported naming:
* correct: LICENSE, license
* commonly misspelled: LICENCE, licence
* Supported formats: no extension, .md, .txt
<s>To Do: tests</s>
Closes #870
> Add support for misspelled license name

- src/publish.ts
Fixes https://github.com/microsoft/vscode-vsce/issues/868
When publishing multiple `vsix` packages with different target platforms using the `--packagePath` flag and the `--skip-duplicate` flag, only the first package is published. After that, all the others are considered duplicate versions and are not published.
Always consider the target platform along with the version when the `target` is present in the publish options
I did not see any relevant test cases for this code, so please let me know if I missed it and I will update the PR.
Thanks!
FYI @mbehr1
> (#868) publish option --skip-duplicate doesn't consider target platforms

- src/main.ts
This trips me up every time I use vsce. npm uses 'npm pack', and vsce uses 'vsce package', so add an alias to save me a collective dozen seconds over the course of my life
> add a pack alias for package

- package-lock.json
- package.json
- src/main.ts
Resolves #769 
This PR adds basic user-friendly message as a description, which is expected to appear at every command passed with the `--help` flag. The current `commander` version (6.1.0) doesn't support certain commands that help adding this message properly (like only for the 'root' help), as well as other commands that potentially can be helpful in optimizing the current code and removing the parts that `commander` has implemented under-the-hood (like showing suggestions on errors).
So I would highly suggest creating an issue to proceed with migration to version [8.2.0](https://github.com/tj/commander.js/releases/tag/v8.2.0) at least. And I would love to help you with that migration.
> feat: add user-friendly info to --help

- package-lock.json
- package.json
- src/publish.ts
- src/store.ts
- src/util.ts
Change to use to the new azure-devops-node-api method for calling publisher signing endpoint.
> Use NodeApi

- package-lock.json
- package.json
- src/publish.ts
This pull request adds retry functionality to the publishing process in order to handle API request timeouts. Currently, when the connection between where `vsce` is running and the Marketplace API times out, the publishing fails. The proposed solution is to automatically retry the API request a few times with a backoff in between. 
For convinience, the `cockatiel` library was used which is why the node version had to be incresed to `>=16` 
fixes #926
> Retry on API request timeout

- src/nls.ts
Throw Error if NLS id does not exist in available translations
> Validate NLS strings

- package-lock.json
- package.json
- src/main.ts
- src/package.ts
- src/publish.ts
enable signing in vsce using script
- add `--sign` script argument for signing the manifest
- enable package and publish to sign the package using `@vscode/vsce-sign` package and sign script
> enable signing in vsce using script

- Dockerfile
The Dockerfile is currently using `node:14-alpine` as the base image, which is not compatible with the required Node.js version of >= 18.x.x stated in the README. This results in a broken image. This pull request updates the Dockerfile to use `node:18-alpine` as the base image, resolving the issue.
> Update Dockerfile to use node:18-alpine

- src/main.ts
- src/package.ts
- src/store.ts
- src/util.ts
When packaging, inform the user on which files/folders are being packaged.
fixes #995
> Print packaged files/folders

- src/main.ts
- src/package.ts
- src/util.ts
This pull request improves the `ls` command by adding a new `--tree` option. When this option is used, the command will print the files in a tree format. This makes it easier to visualize the file structure of the extension.
> Support "ls --tree"

- src/main.ts
- src/package.ts
- src/publish.ts
- src/util.ts
- src/zip.ts
fixes https://github.com/microsoft/vscode-vsce/issues/1016
> Throw when unused files pattern in package.json

- src/package.ts
> Throw error if provided readmePath or provided changelogPath could not be found

- src/main.ts
- src/package.ts
> Don't package default readme if a path is provided and default is ignored

- src/npm.ts
There is a probability of triggering a v8 crash when running the `yarn list --prod --json` command. Related discussion: https://github.com/nodejs/node/issues/51555
This issue does not always occur. When we build `vscode-reh-linux-arm64` in the Dockerfile, there is more than a 50% chance of failure.
If this PR is merged, the code related to DISABLE_V8_COMPILE_CACHE in vscode can also be removed (https://github.com/search?q=repo%3Amicrosoft%2Fvscode%20DISABLE_V8_COMPILE_CACHE&type=code).
Globally setting `DISABLE_V8_COMPILE_CACHE=1` will increase the entire build time by 3~5 minutes.
People possibly related to this: @deepak1556
> fix: probabilistic trigger v8 crash

- src/manifest.ts
- src/nls.ts
- src/package.ts
- src/publish.ts
- src/store.ts
- src/test/package.test.ts
- src/util.ts
- src/validation.ts
- src/zip.ts
This pull request includes changes to the validation of the publisher field in the package manifest. Previously, the validation was triggered even if no publisher was set. With this change, the validation is only performed if a publisher is specified, allowing users to package an extension without a publisher for testing purposes.
fixes #1029
> Allow packaging extension without a publisher

- package-lock.json
- package.json
Fix #930
`markdown-it<14` depended on `punycode`, which has now been deprecated in Node 22. Updating this dependency resolves the warning.
> Fix punycode deprecation warning

- src/main.ts
- src/package.ts
> add verify-signature command. Fixes #1044

- src/package.ts
vsce package --help shows 
```
Usage: vsce package|pack [options] [version]
Packages an extension
Options:
-o, --out <path>                Output .vsix extension file to <path> location (defaults to <name>-<version>.vsix)
...
--allow-missing-repository      Allow missing a repository URL in package.json
--allow-unused-files-pattern    Allow include patterns for the files field in package.json that does not match any file
...
```
But the errors messages says: 
```
The following include patterns in the "files" property in package.json do not match any files packaged in the extension:
- LICENSE
Remove any include pattern which is not needed.
=> Run vsce ls --tree to see all included files.
=> Use --allow-unused-files-patterns to skip this check
``` 
This PR propoes to remove the "s" from the …
> Fix typo in option hint

- src/publish.ts
Resolve https://github.com/microsoft/vscode-vsce/issues/1059.
This change quotes the `filename` value of the `Content-Disposition` header to ensure that file names with special characters are handled properly.
CC @sandy081, @sbanni
> Quote `filename` value in `Content-Disposition` header

- src/main.ts
- src/package.ts
- src/publish.ts
See my comment in https://github.com/microsoft/vscode-vsce/issues/580#issuecomment-2357922938
While upgrading from vsce 2.3 to 3.1, I had this regression which prevented building my package.
I use the following `package.json` extract:
```json
"workspaces": [
"src/lib"
]
```
And this folder is a symlink.
If a workdir was refering a symlink directory, we would pass it to yazl, which would error out because it's a directory.
glob recommends using `follow: true` to consider directory symlinks as directories in the collection.
> Fix regression with workdir symlinks

- src/main.ts
This pull request updates the logging level for the notification regarding the `vsce` version being out of date from INFO to WARNING. This change aims to encourage users to keep their `vsce` installation up to date, enhancing overall user experience and ensuring they are using the latest features and fixes.
Fixes #1064
> Change vsce update notification from INFO to WARNING

- src/api.ts
- src/publish.ts
Exposed unpublish function to the `api.ts` file so it can be used as a node package.  We personally use vsce this way.
Notes:
- Exposes `unpublish` function and `IUnpublishOptions`
- Makes the choice to default `force` to true for IUnpublishOptions because no prompt is available when running as a node package.
> Added unpublish to api.ts

- src/package.ts
- src/test/package.test.ts
Running the same build produces .vsix package that have the same content, but are not bit for bit the same, making it somewhat complicated to verify reproducible builds. Two changes are needed to fix this:
1. The mtime of each file added to the .vsix archive is included in each archive entry, so builds that happen at different times will have different entry timestamps. To fix this, if the SOURCE_DATE_EPOCH environment variable is defined, it it now used as entry timestamp value instead. Builds will now be reproducible as long as they set the same SOURCE_DATE_EPOCH value. If the environment variable is not defined or is not an integer, the current behavior is used.
2. The order that files are collected in preparation for packaging into the .vsix file is non-deterministic, which can lead …
> Allow for reproducible .vsix packages

- package-lock.json
- package.json
- src/main.ts
Refactor command line parameters to ensure consistent styling, specifically changing `--noVerify` to `--no-verify`. Additionally, update the `commander` package to the latest version for better functionality.
Fixes #719
> Update command line parameters for consistency

- src/package.ts
- src/test/package.test.ts
```Copilot Generated Description:``` Eliminate the 'github-copilot' tag from the chat participants and language model tool contributions as it is no longer used.
Fixes microsoft/vscode-vsce#1121
> Remove unused 'github-copilot' tag

- src/package.ts
- src/test/package.test.ts
Introduce support for the 'mcp' tag in the TagsProcessor and add a corresponding test case to ensure correct functionality.
closes https://github.com/microsoft/vscode-vsce/issues/1134
> Add 'mcp' tag support in TagsProcessor

- src/package.ts
- src/test/package.test.ts
```Copilot Generated Description:``` Introduce the `language-model-tools` tag for MCP extensions in the package configuration and update related tests to reflect this change.
closes https://github.com/microsoft/vscode-vsce/issues/1140
> Add `language-model-tools` tag for MCP extensions

- src/main.ts
- src/package.ts
- src/publish.ts
- src/secretLint.ts
- src/test/package.test.ts
```Copilot Generated Description:``` Introduce command line options to allow packaging specific secrets, all kinds of secrets, and .env files. Update the packaging process to validate these options and handle potential security issues accordingly.
closes https://github.com/microsoft/vscode-vsce/issues/1136
closes https://github.com/microsoft/vscode-vsce/issues/1135
> Allow packaging .env and secrets using command line flags

- src/main.ts
- src/package.ts
- src/secretLint.ts
```Copilot Generated Description:``` Adjust the scanning logic to only check for secrets when the corresponding options for packaging all secrets and .env files are not enabled. Update related error messages and linting configurations accordingly.
> Only scan secrets when .env is ignored and vice versa

- src/package.ts
The order of the extension + mime types listed in the [Content_Types].xml file is dependent on the order files are listed in the files array, which can vary depending on the underlying filesystem's traversal order. This can lead to non-reproducible .vsix files.
This sorts the contentTypes array to ensure the order is always consistent and reproducible, regardless of the order of the files array, ensuring reproducible .vsix files.
> Make the [Content_Types].xml file deterministic

- src/package.ts
- src/test/package.test.ts
```Copilot Generated Description:``` Enable the use of dots in tags while maintaining the previous behavior for extension tags. Add a test to verify the changes.
> Allow dots in tags and update extension tag handling

- package.json
I'm working on making this tool compatible with [`deno`](https://deno.com/) and [`bun`](https://bun.sh/) for a personal project. It looks like I'm not the only one who would like to add that support (See: #1108)
Modern JS standards suggest either using a `.cjs` extension or a module `type` declaration on a package to know whether something is a commonjs module or an esm module. See: https://nodejs.org/api/packages.html#packagejson-and-file-extensions
This change adds the missing `"type": "commonjs"` annotation to the package.json file to allow `deno` to run the files correctly.
> add `commonjs` annotation to package.json

- src/package.ts
* Fixes the Node.js `DEP0190` deprecation warning:
```
[DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities...
```
* Replaces the deprecated pattern:
```ts
spawn(tool, ['run', 'vscode:prepublish'], { shell: true, ... });
```
with the safe and supported string form:
```ts
spawn(`${tool} run vscode:prepublish`, { shell: true, ... });
```
* Starting with Node.js 20, using `shell: true` with an argument array triggers a warning and is discouraged.
* This is a well-known Node.js issue documented here:
[https://github.com/nodejs/node/issues/58763](https://github.com/nodejs/node/issues/58763)
* The `tool` value is controlled (`npm` or `yarn`), no user input is involved.
* The command is static and cannot be exploited.
* This …
> Avoid Node.js DEP0190 warning by using string form for prepublish command

- src/package.ts
- src/test/package.test.ts
Autogenerating `language-model` tags doesn't currently work, which seems to be because the contribution was renamed 4 weeks ago: https://github.com/microsoft/vscode/blob/f9618ba2a9749ee72df385329c56208eefdb3ef9/src/vs/workbench/contrib/chat/common/languageModels.ts#L290-L291
cc @benibenj @isidorn
> fix: generate language model tag for `languageModelChatProvider` contributions
